import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, ArrowUpLeft, LockKeyhole } from "lucide-react";
import { pageHead } from "@/components/site/PageMeta";
import hero from "@/assets/gulfwellbeing-hero.jpg";
import woman from "@/assets/woman-editorial.jpg";
import executive from "@/assets/executive-editorial.jpg";
import stillLife from "@/assets/private-still-life.jpg";

export const Route=createFileRoute("/ar")({
  head:()=>pageHead("GULFWELLBEING | استشارات Wellbeing خاصة","استشارات Wellbeing وتوجيه شخصي خاص وسري مع Sourour Tarkan للأفراد والعائلات والقيادات."),
  component:ArabicHome
});

function ArabicHome(){return <div dir="rtl" className="min-h-screen bg-background text-foreground">
<header className="fixed inset-x-0 top-0 z-50 border-b border-border/40 bg-background/90 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-[1440px] items-center justify-between px-5 lg:px-10"><Link to="/ar" className="font-serif text-2xl tracking-wide">GULFWELLBEING</Link><nav className="hidden items-center gap-7 text-sm xl:flex"><a href="#wellbeing">Wellbeing</a><a href="#areas">المجالات</a><a href="#vip">VIP Concierge</a><a href="#approach">النهج</a><Link to="/book" className="button-gold">احجز جلسة خاصة</Link><Link to="/" className="text-gold">English</Link></nav><Link to="/book" className="text-sm text-gold xl:hidden">احجز</Link></div></header>
<main className="pt-20">
<section className="relative min-h-[calc(100svh-5rem)] overflow-hidden bg-primary text-primary-foreground"><img src={hero} alt="جلسة Wellbeing خاصة وسرية" className="absolute inset-0 size-full object-cover"/><div className="absolute inset-0 bg-linear-to-l from-primary via-primary/70 to-transparent"/><div className="relative mx-auto flex min-h-[calc(100svh-5rem)] max-w-[1500px] items-end px-6 pb-16 lg:px-12 lg:pb-24"><div className="max-w-4xl"><p className="eyebrow text-gold">PRIVATE WELLBEING ADVISORY · GCC & INTERNATIONAL</p><h1 className="mt-6 font-serif text-6xl leading-[.9] sm:text-8xl">لمن يحمل<br/><em className="font-normal">الكثير.</em></h1><p className="mt-8 max-w-2xl text-base leading-8 text-primary-foreground/75 sm:text-lg">مساحة خاصة وسرية مع Sourour Tarkan للتعامل مع الضغط، العلاقات، المسؤوليات، التغيير والقيادة بوضوح أكبر.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/book" className="button-gold">طلب جلسة خاصة <ArrowLeftIcon/></Link><a href="#areas" className="button-on-dark">استكشف المجالات</a></div></div></div></section>

<section id="wellbeing" className="px-6 py-20 lg:px-12 lg:py-32"><div className="mx-auto grid max-w-[1400px] gap-12 lg:grid-cols-[.7fr_1.3fr]"><p className="eyebrow">PRIVATE ADVISORY</p><div><h2 className="font-serif text-5xl leading-none sm:text-7xl">Wellbeing شخصي.<br/>ودعم يليق بخصوصية حياتك.</h2><p className="mt-7 max-w-2xl text-base leading-8 text-muted-foreground">Gulfwellbeing يقدم مساحة هادئة وسرية للتفكير، استعادة المنظور والتعامل مع مراحل الحياة المعقدة. لا يوجد برنامج واحد للجميع؛ يبدأ العمل من الشخص وظروفه وأولوياته.</p></div></div></section>

<section id="areas" className="bg-secondary px-6 py-20 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1500px]"><p className="eyebrow">المجالات</p><h2 className="mt-4 font-serif text-5xl sm:text-7xl">مسارات خاصة</h2><div className="mt-12 grid gap-px bg-border md:grid-cols-2"><Card title="Private Wellbeing" text="الضغط، التوازن العاطفي، العلاقات، الحضور، التغيير واستعادة الطاقة." image={stillLife} href="/wellbeing"/><Card title="Women's Wellbeing" text="الأمومة، الحياة العائلية، الثقة بالنفس، العلاقات والتحولات الشخصية." image={woman} href="/women"/><Card title="Men's Wellbeing" text="المسؤولية، الأبوة، الضغط، القيادة والتوازن الشخصي." image={executive} href="/men"/><Card title="Business & Executive" text="Executive wellbeing، وضوح القيادة، الوقاية من الاحتراق والدعم الخاص للقيادات." image={executive} href="/business"/></div></div></section>

<section id="vip" className="grid bg-primary text-primary-foreground lg:grid-cols-2"><img src={stillLife} alt="بيئة خاصة وراقية للاستشارة" className="min-h-[30rem] w-full object-cover"/><div className="flex items-center px-6 py-20 lg:px-20"><div className="max-w-xl"><LockKeyhole className="size-5 text-gold"/><p className="eyebrow mt-7 text-gold">VIP CONCIERGE WELLBEING</p><h2 className="mt-5 font-serif text-5xl leading-none sm:text-7xl">مستوى أكثر خصوصية.</h2><p className="mt-7 text-base leading-8 text-primary-foreground/70">تجربة مخصصة للأشخاص والعائلات والقيادات ذات الجداول المكثفة والحياة الدولية، مع مرونة وسرية عالية.</p><Link to="/business/vip-concierge-wellbeing" className="button-gold mt-9">اكتشف VIP Concierge</Link></div></div></section>

<section id="approach" className="px-6 py-20 lg:px-12 lg:py-32"><div className="mx-auto grid max-w-[1300px] gap-12 lg:grid-cols-2"><div><p className="eyebrow">النهج</p><h2 className="mt-4 font-serif text-5xl leading-none sm:text-7xl">اهتمام إنساني<br/>دون افتراضات.</h2></div><div className="text-base leading-8 text-muted-foreground"><p>العمل هادئ، شخصي ومدروس، مع احترام تعقيد الحياة الواقعية. يمكن أن يركز على wellbeing الشخصي، العلاقات، الأسرة، الانتقال، القيادة أو الضغوط التي يصعب الحديث عنها في أماكن أخرى.</p><p className="mt-6">وعند ملاءمته وبموافقة الشخص، يمكن أن تتضمن الجلسات ممارسات holistic wellbeing وReiki. Sourour Tarkan هي Reiki Master.</p><Link to="/about" className="mt-8 inline-flex items-center gap-2 border-b border-foreground pb-2 text-sm">تعرف على Sourour Tarkan <ArrowUpLeft className="size-4"/></Link></div></div></section>

<section className="bg-secondary px-6 py-20 lg:px-12 lg:py-28"><div className="mx-auto max-w-4xl text-center"><p className="eyebrow text-gold">PRIVATE ENQUIRY</p><h2 className="mt-5 font-serif text-5xl sm:text-7xl">ابدأ بمحادثة خاصة.</h2><p className="mx-auto mt-6 max-w-2xl text-base leading-8 text-muted-foreground">Book a Session هو طلب خاص، وليس حجزاً آلياً. يتم مراجعة الطلب شخصياً ثم التواصل معك بالطريقة التي تختارها.</p><Link to="/book" className="button-primary mt-9">طلب جلسة خاصة</Link><div className="mt-6"><Link to="/" className="text-sm text-gold">Back to English version</Link></div></div></section>
</main><footer className="bg-primary px-6 py-10 text-center text-sm text-primary-foreground/60">© {new Date().getFullYear()} GULFWELLBEING · <Link to="/privacy">Privacy</Link> · <Link to="/terms">Terms</Link></footer>
</div>}
function ArrowLeftIcon(){return <ArrowRight className="size-4 rotate-180"/>}
function Card({title,text,image,href}:{title:string;text:string;image:string;href:string}){return <Link to={href as any} className="group relative min-h-[28rem] overflow-hidden bg-primary text-primary-foreground"><img src={image} alt="" className="absolute inset-0 size-full object-cover opacity-60 transition-transform duration-700 group-hover:scale-[1.025]"/><div className="absolute inset-0 bg-linear-to-t from-primary via-primary/20 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-7"><h3 className="font-serif text-4xl">{title}</h3><p className="mt-3 max-w-md text-sm leading-7 text-primary-foreground/70">{text}</p><ArrowUpLeft className="mt-6 size-5"/></div></Link>}
