import { createFileRoute,Link,useLocation } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { SiteShell } from "@/components/site/SiteShell";
import { JournalArticle } from "@/components/site/JournalArticle";
import { pageHead, pageHeadFor } from "@/components/site/PageMeta";
import stillLife from "@/assets/private-still-life.jpg";

export const Route=createFileRoute("/blog")({
  head: (ctx) => pageHeadFor(ctx, "Private Wellbeing Blog | GULFWELLBEING","Original perspectives on private wellbeing, relationships, leadership, executive pressure and life transitions across the Gulf and internationally.","/blog"),
  component:Page
});
const categories=["Wellbeing","Leadership","Women","Men","Relationships","Life Transitions","Executive Wellbeing"];
const articles=[
["private-wellbeing-advisory-gulf","PRIVATE WELLBEING ADVISORY","Private Wellbeing Advisory in the Gulf: What a More Personal Approach Can Offer","A considered introduction to private wellbeing advisory for individuals and families living with demanding personal or professional lives.",["A different kind of support","Private wellbeing advisory is not built around a standard programme. It begins with the person's context: the responsibilities they carry, the relationships that matter, the changes underway and the areas where more clarity would be useful."],["Why privacy matters","For executives, entrepreneurs, families and public-facing professionals, the ability to speak without performing a role can be valuable. A discreet advisory relationship creates room to examine pressure, boundaries, decisions and personal priorities away from everyday demands."],["What sessions may explore","Depending on the agreed focus, conversations may touch on stress, emotional balance, relationships, confidence, life transitions, mindfulness or holistic wellbeing. The emphasis is on the individual rather than a fixed formula."]],
["stress-burnout-executives","EXECUTIVE WELLBEING","Stress and Burnout in Executives","Creating space before sustained pressure takes over.",["When pressure becomes constant","Sustained responsibility can make pressure feel ordinary. Private space can help identify what is demanding attention and what needs to change."],["The value of perspective","A confidential conversation creates room to examine boundaries, priorities and the human side of performance without reducing a complex situation to a formula."],["A personal approach","The focus remains on the individual, their context and the changes they are ready to explore."]],
["womens-wellbeing-gulf","WOMEN'S WELLBEING","Women's Wellbeing in the Gulf","Identity, relationships, family life, confidence and transitions.",["A whole-person perspective","Women's wellbeing can be shaped by family, relationships, identity, work and private responsibilities at the same time."],["Private reflection","A confidential setting allows space to explore what is changing and what matters personally."],["Moving forward","The work is shaped around the individual rather than a predefined programme."]],
["mens-wellbeing-pressure","MEN'S WELLBEING","Men's Wellbeing","The pressure behind responsibility, fatherhood and leadership.",["Beyond the role","Responsibility can leave little room to consider the person behind the role."],["A private space","Confidential conversation can create room for reflection, emotional balance and clearer priorities."],["Personal direction","The focus is on what the individual is navigating and what meaningful change could look like."]],
["relationships-family-wellbeing","RELATIONSHIPS & FAMILY","Relationships & Family Wellbeing","Making space for communication, boundaries and what matters.",["Understanding dynamics","Relationships are shaped by context, expectations and patterns of communication."],["Boundaries and clarity","Private reflection can help clarify needs, boundaries and priorities."],["A considered conversation","The aim is not a fixed formula, but a space to understand what is happening and what may help."]],
["life-transitions-wellbeing","LIFE TRANSITIONS","Life Transitions & Wellbeing","Finding perspective when familiar roles and priorities change.",["When life changes","Transitions can affect identity, relationships, routines and priorities."],["Making sense of change","A private conversation can create room to understand what has changed and what matters next."],["A new direction","The process is shaped around the person's circumstances and pace."]],
["mindfulness-busy-lives","MINDFULNESS","Mindfulness for Busy Lives","Creating presence when life leaves little room to pause.",["Making room to pause","Busy lives can make constant activity feel normal. Mindfulness begins with creating moments of awareness."],["Presence and perspective","Simple reflective practices can support greater awareness of thoughts, emotions and everyday patterns."],["Personal practice","The approach is adapted to the person's life rather than imposed as a rigid routine."]],
["emotional-balance-private-wellbeing","EMOTIONAL BALANCE","Emotional Balance & Private Wellbeing","Understanding emotional patterns without reducing a complex life to a formula.",["Emotions in context","Emotional experience is connected to circumstances, relationships and responsibilities."],["Understanding patterns","Reflection can help identify recurring reactions and the situations that shape them."],["Creating space","Private support offers room to consider responses with greater awareness."]],
["confidence-self-trust","CONFIDENCE & SELF-TRUST","Confidence & Self-Trust","A private perspective on confidence, boundaries and personal direction.",["Confidence and context","Confidence is influenced by experience, relationships and the stories people carry about themselves."],["Trusting your perspective","Private reflection can help distinguish external expectations from personal priorities."],["Moving with clarity","The goal is greater awareness of what feels authentic and relevant to the individual."]],
["leadership-clarity-private-advisory","LEADERSHIP","Leadership Clarity","Why senior responsibility sometimes needs private space to think.",["The weight of responsibility","Leadership involves decisions, people responsibility and competing priorities."],["A private thinking space","Advisory conversation creates room to step outside the immediate demands and consider the wider picture."],["Clarity before action","The emphasis is on understanding context before deciding what needs to change."]],
["family-life-gulf-wellbeing","FAMILY & PRIVATE LIFE","Family Life & Wellbeing in the Gulf","Family responsibility, relationships and the personal space in between.",["The complexity of family life","Family wellbeing can involve multiple roles, expectations and relationships."],["Private perspective","A confidential space can help make sense of tensions and competing responsibilities."],["What matters","The conversation stays centred on the person and the realities of their private life."]],
["private-wellbeing-high-responsibility","PRIVATE WELLBEING","Private Wellbeing for High-Responsibility Lives","When responsibility becomes the background to everything.",["Living with responsibility","High responsibility can shape how a person thinks, rests, relates and makes decisions."],["Space away from the role","Private advisory offers a place to consider the person behind the responsibilities."],["A whole-person approach","The focus includes wellbeing, context, relationships and personal direction."]]
] as const;
function ArticleFallback({article}:{article:typeof articles[number]}){return <JournalArticle eyebrow={article[1]} title={article[2]} description={article[3]} sections={article.slice(4) as [string,string][]} related={[{label:"Private Wellbeing",to:"/wellbeing"},{label:"Women's Wellbeing",to:"/women"},{label:"Men's Wellbeing",to:"/men"},{label:"Business Wellbeing",to:"/business"},{label:"The Tarkan Approach",to:"/the-tarkan-approach"}]}/>}
function Page(){const location=useLocation();const slug=location.pathname.startsWith("/blog/")?location.pathname.split("/").filter(Boolean)[1]:"";const article=articles.find(a=>a[0]===slug);if(article)return <ArticleFallback article={article}/>;return <SiteShell><section className="page-hero"><div className="mx-auto grid min-h-[68vh] max-w-[1440px] items-center gap-12 px-6 py-20 lg:grid-cols-2 lg:px-12"><div><p className="eyebrow text-gold">THE PRIVATE JOURNAL</p><h1 className="mt-6 font-serif text-6xl md:text-8xl">Perspectives for a more considered life.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground">Occasional reflections on wellbeing, relationships, leadership, personal change and the realities of a demanding life.</p></div><img src={stillLife} width={1408} height={1008} alt="A private journal and writing desk" className="h-[50vh] w-full object-cover"/></div></section><section className="mx-auto max-w-[1440px] px-6 py-20 lg:px-12"><div className="flex flex-wrap gap-3">{categories.map(c=><span key={c} className="border border-border px-4 py-2 text-xs uppercase tracking-[.12em]">{c}</span>)}</div><div className="mt-16 grid gap-px bg-border md:grid-cols-2 lg:grid-cols-3">{[
["Private Wellbeing Advisory in the Gulf","A personal approach for individuals and families living with demanding lives.","/blog/private-wellbeing-advisory-gulf"],["Stress and Burnout in Executives","Creating space before sustained pressure takes over.","/blog/stress-burnout-executives"],["Women's Wellbeing in the Gulf","Identity, relationships, family life, confidence and transitions.","/blog/womens-wellbeing-gulf"],["Men's Wellbeing","The pressure behind responsibility, fatherhood and leadership.","/blog/mens-wellbeing-pressure"],["Relationships & Family Wellbeing","Making space for communication, boundaries and what matters.","/blog/relationships-family-wellbeing"],["Life Transitions & Wellbeing","Finding perspective when familiar roles and priorities change.","/blog/life-transitions-wellbeing"],["Mindfulness for Busy Lives","Creating presence when life leaves little room to pause.","/blog/mindfulness-busy-lives"],["Emotional Balance & Private Wellbeing","Understanding emotional patterns without reducing a complex life to a formula.","/blog/emotional-balance-private-wellbeing"],["Confidence & Self-Trust","A private perspective on confidence, boundaries and personal direction.","/blog/confidence-self-trust"],["Leadership Clarity","Why senior responsibility sometimes needs private space to think.","/blog/leadership-clarity-private-advisory"],["Family Life & Wellbeing in the Gulf","Family responsibility, relationships and the personal space in between.","/blog/family-life-gulf-wellbeing"],["Private Wellbeing for High-Responsibility Lives","When responsibility becomes the background to everything.","/blog/private-wellbeing-high-responsibility"]].map(([title,text,to],i)=><div key={to} className="group relative z-10 bg-background p-7 transition-colors hover:bg-secondary"><span className="text-xs text-gold">0{i+1}</span><Link to={to} className="relative z-20 block cursor-pointer"><h2 className="mt-10 font-serif text-3xl leading-tight hover:underline">{title}</h2></Link><p className="mt-4 text-sm leading-7 text-muted-foreground">{text}</p><Link to={to} className="relative z-20 mt-6 inline-flex cursor-pointer items-center gap-2 text-sm">Read the perspective <ArrowRight className="size-4 transition-transform group-hover:translate-x-1"/></Link></div>)}</div></section></SiteShell>}