import { createFileRoute,Link } from "@tanstack/react-router";
import { ArrowRight,Check } from "lucide-react";
import { SiteShell } from "@/components/site/SiteShell";
import { pageHead } from "@/components/site/PageMeta";
import stillLife from "@/assets/private-still-life.jpg";

export const Route=createFileRoute("/business/vip-concierge-wellbeing")({
  head:()=>pageHead("Private Concierge Wellbeing — GULFWELLBEING","Private concierge wellbeing advisory by enquiry for individuals, families and executives across the Gulf and internationally."),
  component:Page
});
const features=["Private wellbeing advisory","Flexible session arrangements","Priority scheduling where available","Personalised wellbeing planning","Executive and leadership support","Family and private-life support","Travel-compatible sessions","Remote international sessions"];
function Page(){return <SiteShell><section className="relative min-h-[88vh] bg-primary text-primary-foreground"><img src={stillLife} width={1408} height={1008} alt="An exclusive private advisory setting" className="absolute inset-0 size-full object-cover opacity-45"/><div className="absolute inset-0 bg-vip-overlay"/><div className="relative mx-auto flex min-h-[88vh] max-w-[1440px] items-end px-6 pb-20 lg:px-12"><div className="max-w-4xl"><p className="eyebrow text-gold">BY PRIVATE ENQUIRY</p><h1 className="mt-6 font-serif text-6xl leading-none md:text-8xl">Private Concierge<br/>Wellbeing</h1><p className="mt-7 max-w-xl text-xl leading-8 text-primary-foreground/70">A more flexible, personal level of support for clients whose circumstances require discretion and adaptability.</p><Link to="/book" className="button-gold mt-9">Request a Private Consultation <ArrowRight className="size-4"/></Link></div></div></section><section className="bg-primary text-primary-foreground"><div className="mx-auto grid max-w-[1440px] gap-16 px-6 py-24 lg:grid-cols-[.8fr_1.2fr] lg:px-12"><div><p className="eyebrow text-gold">A PRIVATE STANDARD</p><h2 className="mt-6 font-serif text-5xl">Designed around your life, not a fixed format.</h2></div><div><p className="max-w-2xl text-lg leading-8 text-primary-foreground/65">Private concierge arrangements are considered individually. Frequency, format, scheduling and areas of focus can be discussed around the realities of your personal or professional life.</p><div className="mt-12 grid gap-5 sm:grid-cols-2">{features.map(f=><div key={f} className="flex items-center gap-3 border-t border-primary-foreground/15 pt-5"><Check className="size-4 text-gold"/><span>{f}</span></div>)}</div><p className="mt-12 text-sm text-primary-foreground/55">Specific arrangements, availability and fees are discussed privately and remain subject to agreement.</p></div></div></section><section className="px-6 py-24 text-center"><p className="eyebrow text-gold">TAILORED AVAILABILITY</p><h2 className="mx-auto mt-5 max-w-3xl font-serif text-5xl">The first step is a private conversation.</h2><Link to="/book" className="button-primary mt-8">Request a Private Consultation</Link></section></SiteShell>}
