import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Check, LockKeyhole } from "lucide-react";
import { SiteShell } from "@/components/site/SiteShell";
import { pageHead, pageHeadFor } from "@/components/site/PageMeta";
import stillLife from "@/assets/private-still-life.jpg";

export const Route=createFileRoute("/business/vip-concierge-wellbeing")({
  head: (ctx) => pageHeadFor(ctx, "VIP Concierge Wellbeing | Private Wellbeing Advisory | GULFWELLBEING","Private VIP concierge wellbeing advisory for individuals, families, executives and international clients seeking discretion, flexibility and personalised support."),
  component:Page
});
const features=["Private wellbeing advisory","Flexible session arrangements","Priority scheduling where available","Personalised wellbeing planning","Executive and leadership support","Family and private-life support","Travel-compatible sessions","Remote international sessions"];
function Page(){return <SiteShell>
<section className="relative min-h-[88vh] bg-primary text-primary-foreground"><img src={stillLife} width={1408} height={1008} alt="Private VIP concierge wellbeing advisory setting" className="absolute inset-0 size-full object-cover opacity-45"/><div className="absolute inset-0 bg-vip-overlay"/><div className="relative mx-auto flex min-h-[88vh] max-w-[1440px] items-end px-6 pb-20 lg:px-12"><div className="max-w-4xl"><p className="eyebrow text-gold">VIP CONCIERGE WELLBEING · BY PRIVATE ENQUIRY</p><h1 className="mt-6 font-serif text-6xl leading-none md:text-8xl">Private Concierge<br/>Wellbeing</h1><p className="mt-7 max-w-2xl text-xl leading-8 text-primary-foreground/70">A discreet, flexible level of private wellbeing advisory for clients whose personal or professional circumstances require greater adaptability and continuity.</p><Link to="/book" className="button-gold mt-9">Request a Private Consultation <ArrowRight className="size-4"/></Link></div></div></section>

<section className="mx-auto max-w-4xl px-6 py-24 lg:px-12"><p className="eyebrow text-gold">WHAT VIP CONCIERGE MEANS</p><h2 className="mt-5 font-serif text-5xl md:text-6xl">Support designed around the realities of your life.</h2><div className="mt-8 space-y-6 text-lg leading-8 text-muted-foreground"><p>Private concierge wellbeing is intended for clients who value discretion, flexibility and a highly personal approach. Rather than asking you to fit a fixed programme, arrangements can be discussed around your schedule, location and priorities.</p><p>This may be particularly relevant to executives, founders, families and international clients whose professional and personal commitments require a more adaptable format.</p></div></section>

<section className="bg-primary text-primary-foreground"><div className="mx-auto grid max-w-[1440px] gap-16 px-6 py-24 lg:grid-cols-[.8fr_1.2fr] lg:px-12"><div><p className="eyebrow text-gold">A PRIVATE STANDARD</p><h2 className="mt-6 font-serif text-5xl">Designed around your life, not a fixed format.</h2></div><div><p className="max-w-2xl text-lg leading-8 text-primary-foreground/65">Frequency, format, scheduling and areas of focus can be discussed individually. Availability and specific arrangements remain subject to private agreement.</p><div className="mt-12 grid gap-5 sm:grid-cols-2">{features.map(f=><div key={f} className="flex items-center gap-3 border-t border-primary-foreground/15 pt-5"><Check className="size-4 text-gold"/><span>{f}</span></div>)}</div></div></div></section>

<section className="mx-auto max-w-4xl px-6 py-24 lg:px-12"><p className="eyebrow text-gold">FOR INTERNATIONAL & GULF CLIENTS</p><h2 className="mt-5 font-serif text-5xl">Discreet support across changing schedules and locations.</h2><p className="mt-7 text-lg leading-8 text-muted-foreground">For clients based in the GCC or travelling internationally, remote sessions can offer continuity when schedules, travel or location make a conventional arrangement difficult. The appropriate format is discussed privately before any ongoing arrangement begins.</p></section>

<section className="bg-secondary"><div className="mx-auto max-w-4xl px-6 py-24 lg:px-12"><LockKeyhole className="size-9 text-gold"/><p className="eyebrow mt-6 text-gold">PRIVATE & DISCREET</p><h2 className="mt-5 font-serif text-5xl">Begin with a confidential conversation.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">Share only what feels appropriate. We can discuss your circumstances, preferred format, availability and whether a private concierge arrangement is appropriate.</p><Link to="/book" className="button-primary mt-8">Request a Private Consultation <ArrowRight className="size-4"/></Link></div></section>
</SiteShell>}
