import { Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { SiteShell } from "@/components/site/SiteShell";
import stillLife from "@/assets/private-still-life.jpg";

type ArticleProps={eyebrow:string;title:string;description:string;sections:[string,string][];related:{label:string;to:string}[]};
const faqByTitle:Record<string,[string,string][]> = {
"Private Wellbeing Advisory in the Gulf: What a More Personal Approach Can Offer":[["What is private wellbeing advisory?","It is a confidential, personalised space to explore wellbeing, clarity, relationships, personal change and the realities of a demanding life."],["Who is private wellbeing advisory for?","It may be relevant to individuals, families, executives, entrepreneurs and others who value discretion and a highly individual approach."],["Can sessions be held remotely in the Gulf?","Yes. A private advisory relationship can be arranged remotely for clients across Gulf countries and internationally."],["Is wellbeing advisory a substitute for medical or psychological care?","No. Where clinical, medical or psychological care is required, appropriate qualified professionals should be involved."] ],
"Stress and Burnout in Executives":[["What does executive wellbeing advisory explore?","It can explore sustained pressure, boundaries, decision fatigue, relationships, personal priorities and the human side of leadership."],["Is executive wellbeing only about productivity?","No. The approach also considers the person behind the role, including relationships, identity, emotional balance and life outside work."],["Can executives in the Gulf work remotely with an advisor?","Yes. Remote private sessions can provide continuity for leaders who travel or work across Gulf and international locations."],["When should someone seek professional clinical support?","If symptoms or concerns require diagnosis or treatment, qualified medical or mental-health professionals should provide that care."] ],
"Women's Wellbeing in the Gulf":[["What can women's wellbeing sessions explore?","Topics may include confidence, relationships, motherhood, boundaries, emotional balance, transitions and personal priorities."],["Is the approach specific to women living in the Gulf?","The approach is informed by the realities of Gulf life while remaining individual; no single cultural or family experience is assumed."],["Can mothers have a private space for themselves?","Yes. A session can provide dedicated time to consider identity, needs and priorities alongside the responsibilities of motherhood."],["Are sessions confidential?","The service is designed as a discreet private advisory relationship, with appropriate professional boundaries."] ],
"Men's Wellbeing":[["What can men's wellbeing advisory address?","It may explore responsibility, leadership, fatherhood, relationships, confidence, emotional balance, boundaries and personal direction."],["Why might private space be useful for men?","A confidential setting can make it easier to reflect without having to perform a particular role or expectation of strength."],["Is men's wellbeing limited to stress management?","No. It takes a whole-person view that can include relationships, identity, family life and personal priorities."],["Can sessions be remote?","Yes. Remote sessions can support clients living or working across Gulf countries and internationally."] ],
"Relationships & Family Wellbeing":[["Can private wellbeing advisory help with relationship difficulties?","It can provide an individual space to understand patterns, communication, boundaries and personal choices; it is not a substitute for qualified couples or family therapy when that is required."],["Why does Gulf family context matter?","Family structures, expectations and extended relationships can shape private life, so context can be important when considering wellbeing."],["Can I discuss family issues without involving the whole family?","Yes. The advisory relationship can be centred on the individual and their own experience."],["What happens if therapy is needed?","Appropriate qualified therapeutic or clinical support should be sought when the situation calls for it."] ],
"Life Transitions & Wellbeing":[["What kinds of life transitions can be explored?","Relocation, marriage, separation, career change, leadership changes, empty nest and other significant shifts may be explored."],["Why can positive changes still affect wellbeing?","Even welcome changes can alter identity, routines, relationships and expectations, creating a need for adjustment and reflection."],["Can advisory help with difficult decisions?","It can provide structured private reflection and perspective, while leaving decisions with the individual."],["Is there a fixed programme for transitions?","No. The approach is individual and shaped around the person's circumstances and priorities."] ],
"Mindfulness for Busy Lives":[["What does mindfulness mean in a demanding life?","It can mean creating brief moments of awareness and presence within ordinary routines rather than adding another rigid obligation."],["Can mindfulness help busy executives?","It may create space between stimulus and response and support greater awareness during demanding periods."],["Do I need a long daily meditation practice?","Not necessarily. A useful practice should fit the person's circumstances and remain realistic."],["Is mindfulness a treatment for mental-health conditions?","Mindfulness may support wellbeing, but it should not replace appropriate medical or psychological care when that is needed."] ],
"Emotional Balance & Private Wellbeing":[["What does emotional balance mean here?","It means developing greater awareness of emotions, patterns and context rather than trying to eliminate difficult feelings."],["Can emotional patterns be explored privately?","Yes. Private reflection can help identify recurring reactions, boundaries and situations that influence emotional wellbeing."],["Does emotional wellbeing include relationships?","Yes. Relationships, family, work, identity and personal expectations can all influence emotional experience."],["When is professional mental-health care appropriate?","When concerns require diagnosis or treatment, a qualified mental-health professional should be consulted."] ],
"Confidence & Self-Trust":[["What is the difference between confidence and self-trust?","Confidence can vary by situation, while self-trust concerns the ability to listen to your own observations, values and judgement."],["Can confidence be affected by family or cultural expectations?","Yes. Expectations and social context can influence how people define success and make personal choices."],["Can private advisory help with boundaries?","Boundaries can be explored as part of a wider conversation about agency, relationships and personal priorities."],["Is the goal to become more assertive?","Not necessarily. The focus is on a more grounded relationship with your own values, choices and direction."] ],
"Leadership Clarity":[["Why would a leader need private wellbeing advisory?","Senior responsibility can create cognitive and emotional weight, making uninterrupted space for reflection valuable."],["What is leadership clarity?","It is the ability to understand the situation, priorities and personal context clearly enough to make considered choices."],["Does this approach focus only on business performance?","No. It also considers the person behind the leadership role and the impact of work on relationships and private life."],["Can international Gulf-based leaders work remotely?","Yes. Remote sessions can accommodate leaders working across Gulf and international locations."] ],
"Family Life & Wellbeing in the Gulf":[["What does family wellbeing include?","It can include relationships, parenting, partnership, boundaries, extended-family expectations and the individual's own personal space."],["Why can family life become demanding?","Family responsibilities can overlap with professional roles, travel, cultural expectations and responsibilities toward wider family networks."],["Can I focus on my own wellbeing without neglecting my family?","Private reflection can help clarify how to care for personal needs while remaining connected to family responsibilities."],["Is this family therapy?","No. It is individual private wellbeing advisory. Qualified family or couples professionals should be involved where therapy is needed."] ],
"Private Wellbeing for High-Responsibility Lives":[["Who are high-responsibility clients?","They may include founders, executives, entrepreneurs, parents, family decision-makers and others carrying substantial personal or professional responsibility."],["What does constant responsibility affect?","It can influence attention, boundaries, relationships, rest, decision-making and a person's sense of identity."],["Why is privacy important?","People with visible roles may value a space where they can reflect without the expectations attached to their public or professional position."],["Can this support people living across the Gulf?","Yes. Private advisory can be arranged remotely for clients across the GCC and internationally."]
]};

const deepContent:Record<string,[string,string][]> = {
"Private Wellbeing Advisory in the Gulf: What a More Personal Approach Can Offer":[
["Why a private advisory relationship can feel different","In a demanding Gulf environment, personal and professional responsibilities can overlap. A founder may be thinking about a company while also carrying family expectations. An executive may be highly capable at work while having very little private space to process what constant responsibility is doing to everyday life. Private wellbeing advisory creates a dedicated setting in which the whole situation can be considered rather than treating one symptom in isolation."],
["The Gulf context matters","Wellbeing does not exist outside culture, family and environment. Clients living in Dubai, Abu Dhabi, Doha, Riyadh, Jeddah, Kuwait City, Manama or Muscat may be navigating international careers, extended family relationships, frequent travel, high expectations and very full schedules. A useful conversation therefore needs context. The aim is not to impose a generic Western wellness routine, but to understand the person's actual life and what they want to change within it."],
["From pressure to clarity","Private advisory is not about promising a perfect life or removing every difficult circumstance. It is about creating enough perspective to see patterns more clearly. That may mean looking at boundaries, emotional balance, relationships, confidence, decision fatigue, life transitions or the gap between what a person appears to be managing and what they are privately experiencing."],
["A whole-person conversation","The Tarkan Approach begins with the person before the problem. Different areas of life influence one another, so a conversation about stress may naturally include relationships, identity, family, leadership or personal expectations. This broader lens allows the work to remain individual and flexible rather than forcing a client into a predefined programme."],
["Who may seek private wellbeing advisory","Private wellbeing advisory may suit individuals, couples or families who value discretion and a highly personalised relationship. It can also be relevant to executives, entrepreneurs and people living with substantial responsibility. Sessions are arranged privately and can be conducted remotely for clients in the Gulf and internationally."]
],
"Stress and Burnout in Executives":[
["When high performance becomes a permanent state","Executive pressure can be difficult to recognise precisely because functioning continues. Meetings happen, decisions are made and responsibilities are handled, while rest, relationships and personal attention gradually receive less space. The question is not simply whether someone is busy. It is whether constant demand has become the background condition of life."],
["The difference between pressure and perspective","A private wellbeing conversation can create distance from the immediate demands of leadership. That distance can make it easier to examine what is genuinely necessary, what has become habitual and where boundaries have become unclear. The purpose is not to diagnose from a distance, but to create a confidential setting for reflection and considered decisions."],
["Executive wellbeing in the Gulf","Leaders across the Gulf may operate across several cultures, time zones and professional networks. Business growth, family commitments, travel and expectations of availability can create a particularly dense environment. Executive wellbeing therefore benefits from an approach that understands the individual context rather than relying on a generic stress checklist."],
["Beyond productivity","Wellbeing should not be reduced to another performance metric. A private advisory relationship can explore the person behind the role: relationships, identity, emotional balance, personal priorities and the ability to experience life outside work. Sometimes the most useful question is not how to do more, but what deserves attention now."],
["When private support may be useful","A confidential conversation can be considered when pressure feels continuous, decisions are occupying too much mental space, boundaries are becoming difficult to maintain or personal life is consistently being postponed. Where medical or psychological care is needed, wellbeing advisory should sit alongside appropriate qualified professional support rather than replace it."]
],
"Women's Wellbeing in the Gulf":[
["The many dimensions of women's wellbeing","Women's wellbeing can involve several realities at once: professional identity, family life, partnership, motherhood, confidence, expectations and personal aspirations. In Gulf communities, these dimensions may be influenced by family structures, culture and social responsibilities. A private approach allows the conversation to begin with the woman's own circumstances rather than assumptions about what she should want."],
["A space that belongs to the individual","Many women spend substantial time responding to the needs of others. A private session can offer something different: time that is deliberately centred on the individual. It may be used to explore confidence, emotional balance, boundaries, relationships, transitions or the feeling of having lost contact with personal priorities."],
["Women living demanding international lives","For women moving between Gulf cities, international careers and family commitments, continuity can be especially valuable. A remote private advisory relationship can provide a consistent space for reflection even when routines, locations and responsibilities change."],
["Motherhood, identity and change","Motherhood can bring meaning and love while also changing time, identity and expectations. Private wellbeing conversations can explore the tension between caring for others and retaining a sense of self. The objective is not to prescribe one model of motherhood, but to understand the individual's experience."],
["A discreet, whole-person approach","The Tarkan Approach considers the person before the label. Women are not reduced to a role such as mother, partner, professional or caregiver. The conversation can move between these areas according to what is most relevant, with discretion and personal context remaining central."]
],
"Men's Wellbeing":[
["The person behind responsibility","Men who carry responsibility for businesses, families or teams can become accustomed to being the person others rely on. That role can make it difficult to acknowledge uncertainty, pressure or the need for private reflection. A wellbeing advisory relationship creates space to consider the individual without requiring a public performance of strength."],
["Pressure, fatherhood and leadership","Responsibility may come through several channels at once. A man may be managing a company, supporting parents, raising children and maintaining a demanding social or professional schedule. Looking at these pressures together can reveal patterns that are difficult to see when each responsibility is treated separately."],
["Emotional wellbeing without labels","A private conversation does not need to begin with a diagnosis or a predefined problem. It can begin with what feels different, difficult or unresolved. Emotional balance may involve understanding reactions, communicating more clearly, setting boundaries or recognising when constant activity has become a way of avoiding reflection."],
["Men's wellbeing in the Gulf","Across Gulf societies, expectations around family, provision, leadership and social responsibility can be significant. Those expectations are experienced differently by every person. An individual approach makes room for culture and family context without assuming that every man has the same experience."],
["A private space to think","The value of private advisory can be simple: uninterrupted time to think with another person who is focused on the client's context. Sessions can explore relationships, confidence, transitions, stress, mindfulness and personal direction according to the individual's priorities."]
],
"Relationships & Family Wellbeing":[
["Relationships are rarely one-dimensional","Family and relationship difficulties are often connected to several layers at once: communication, expectations, history, responsibilities and personal boundaries. A private wellbeing conversation can help an individual step back from the immediate disagreement and consider the wider pattern."],
["Family life in the Gulf","For families living in the Gulf, private life may include close extended-family relationships, international connections, travel, demanding careers and different cultural expectations within the same household. These realities can enrich family life while also creating complexity. Context matters when considering what support may be useful."],
["Communication and boundaries","Healthy communication is not simply about finding the right sentence. It can require understanding what each person needs, what has become repetitive and where boundaries are unclear. Private reflection can help an individual identify what they can influence and what belongs to another person."],
["When family roles become heavy","Being a partner, parent, adult child or family decision-maker can create competing responsibilities. A person may feel responsible for maintaining harmony while having little room to acknowledge their own needs. Making that tension visible can be an important first step toward greater clarity."],
["A private starting point","Wellbeing advisory is not couples therapy or family therapy unless provided by an appropriately qualified professional. Its role here is to offer the individual a confidential space to understand their experience, consider choices and develop a more considered direction."]
],
"Life Transitions & Wellbeing":[
["Transitions change more than routines","A move, marriage, separation, new leadership role, empty nest, career change or shift in family circumstances can affect identity as much as practical life. Even positive change can require adjustment. Private wellbeing advisory creates space to understand what a transition means personally."],
["Transitions in an international Gulf life","People living in the Gulf may experience frequent transitions: relocating between countries, changing roles, raising children across cultures or adapting to new professional environments. A stable private conversation can provide continuity while external circumstances are changing."],
["Identity and the next chapter","When a familiar role ends or changes, the question can become unexpectedly personal: who am I now? Reflection can help separate inherited expectations from current priorities. The aim is not to rush toward an answer, but to make room for a more authentic direction."],
["Making decisions with perspective","Transitions often create pressure to decide quickly. A private advisory process can slow the conversation down enough to identify what is known, what remains uncertain and which choices genuinely belong to the individual. Clarity does not always mean certainty; sometimes it means knowing the next meaningful step."],
["Moving forward without a formula","There is no universal timeline for adjustment. The Tarkan Approach respects individual pace and circumstances, focusing on context, whole-person wellbeing and the person's own definition of a meaningful next chapter."]
],
"Mindfulness for Busy Lives":[
["Mindfulness without adding another obligation","For someone with an already full calendar, mindfulness can sound like another task to complete. A more practical view is to create brief moments of awareness within ordinary life. The aim is not to escape responsibility, but to change the relationship with constant activity."],
["Why presence matters","When attention is repeatedly divided between messages, meetings, family needs and future decisions, it becomes difficult to notice what is happening internally. Mindful awareness can help a person recognise thoughts, emotions and physical signals before automatically reacting to them."],
["Mindfulness for executives and leaders","Leaders often move rapidly from one decision to another. Short moments of deliberate attention can create a pause between stimulus and response. In private advisory, mindfulness may be discussed as one part of a broader approach to clarity, emotional balance and sustainable wellbeing."],
["A practice that fits real life","A useful practice needs to fit the person's circumstances. Someone travelling between Dubai and London may need a different rhythm from a parent managing a demanding household. The approach should therefore remain adaptable rather than turning mindfulness into a rigid routine."],
["From awareness to choice","The value of mindfulness is not simply feeling calm. Greater awareness can create a little more space to choose how to respond. That space can influence communication, boundaries, decision-making and the way a person moves through demanding periods."]
],
"Emotional Balance & Private Wellbeing":[
["Emotional balance is contextual","Emotions do not appear in isolation. Work pressure, relationships, family expectations, sleep, change and unresolved experiences can all influence how a person feels and reacts. Looking at context can be more useful than trying to label a single emotion as the problem."],
["Recognising recurring patterns","People sometimes notice that the same reaction appears in different situations: withdrawing, becoming overly responsible, avoiding difficult conversations or constantly seeking control. Private reflection can make these patterns easier to observe without judgement."],
["The Gulf context and emotional privacy","In close communities and highly connected professional environments, some people may be cautious about discussing personal matters. A discreet advisory relationship can provide a setting where the conversation is intentionally private and centred on the client's experience."],
["From reaction to awareness","Greater emotional awareness does not mean eliminating difficult feelings. It can mean recognising what a reaction is communicating, understanding its context and choosing a response with more intention. That process is individual and can take time."],
["Whole-person wellbeing","Emotional balance connects with relationships, confidence, physical routines, work and personal meaning. The Tarkan Approach keeps these dimensions connected rather than treating emotional wellbeing as a separate compartment."]
],
"Confidence & Self-Trust":[
["Confidence is more than appearance","A person can appear highly confident while privately questioning decisions, boundaries or direction. Confidence can change across contexts. Understanding where self-trust is strong and where it becomes uncertain can be more useful than trying to perform confidence everywhere."],
["External expectations and personal priorities","Family, culture, professional status and social expectations can influence how people define success. Private reflection can help distinguish what genuinely matters to the individual from what they have learned they are expected to value."],
["Confidence in demanding Gulf environments","Professionals and entrepreneurs in Gulf markets may operate in fast-moving environments with high visibility and significant responsibility. The ability to step back and examine decisions privately can support a more grounded sense of direction."],
["Boundaries and self-trust","Self-trust is often connected to boundaries. Saying yes when a person means no, avoiding necessary conversations or constantly adapting to others can gradually weaken a sense of agency. Exploring these patterns can make personal priorities clearer."],
["A quieter form of confidence","The aim is not to create a louder personality. It is to develop greater trust in one's own observations, values and choices. A private advisory relationship can provide a thoughtful space for that process."]
],
"Leadership Clarity":[
["Leadership creates cognitive weight","Senior leaders rarely carry only one decision at a time. People, strategy, finances, reputation and family responsibilities can compete for attention. Private space can help a leader step outside the stream of decisions long enough to see the larger pattern."],
["Why leaders need a space without an audience","Leadership conversations often have a purpose: solve, decide, reassure or perform. A private advisory relationship can be different. It gives the individual room to think aloud, question assumptions and consider personal factors without needing to produce an immediate answer."],
["Leadership in Gulf markets","Gulf business environments can be international, relationship-driven and fast-moving. Leaders may work across cultures and time zones while maintaining significant family and social responsibilities. Effective wellbeing support needs to recognise this environment without reducing it to stereotypes."],
["Clarity before action","The Tarkan Approach places context before advice. Before deciding what should change, it is useful to understand what is happening, what belongs to the role and what belongs to the person. This can turn an overwhelming situation into a more structured conversation."],
["The human side of leadership","Leadership wellbeing is not only about avoiding burnout. It also concerns relationships, identity, emotional balance, personal meaning and the ability to remain present outside work. A leader is still a person when the working day ends."]
],
"Family Life & Wellbeing in the Gulf":[
["The private side of a demanding life","Family life can be deeply meaningful while also carrying expectations, responsibilities and complex relationships. For people with demanding careers, the home can become another place where decisions need to be made rather than a place where the person can simply be themselves."],
["Extended family and cultural context","Family structures and expectations differ across the Gulf and from one household to another. Extended family may be a source of support, connection and responsibility at the same time. A private approach should make room for that complexity rather than applying a single model of family wellbeing."],
["Balancing professional and private roles","A senior professional may be highly effective at work and still struggle to create boundaries around family time. Private reflection can help identify where availability has become constant and which boundaries would make life more sustainable."],
["Parenting, partnership and personal space","Family wellbeing includes the adults within the family. Partners and parents may need space to consider their own needs as well as the needs of others. That does not mean withdrawing from responsibility; it can mean finding a healthier way to carry it."],
["A discreet place to reflect","Private advisory provides an individual space to consider family dynamics, personal boundaries and life priorities. Where clinical, therapeutic or family-specific treatment is required, appropriate qualified professionals remain essential."]
],
"Private Wellbeing for High-Responsibility Lives":[
["When responsibility becomes an identity","For some people, responsibility is not limited to a job. It can include employees, companies, children, parents, partners, finances and social obligations. Over time, being responsible for everything can become part of identity itself, making it difficult to notice personal needs."],
["The cost of constant availability","Technology has made it possible to remain reachable almost all the time. For high-responsibility individuals, this can blur the boundary between urgent and important. Private reflection can help examine where constant availability is genuinely required and where it has simply become habitual."],
["A Gulf life can be highly connected","International business, family networks, travel and social commitments can make life particularly interconnected. That can be rewarding, but it can also reduce opportunities for uninterrupted reflection. A confidential advisory relationship can provide a deliberate counterbalance."],
["The person before the role","The Tarkan Approach starts with the person rather than the title they hold. Founder, executive, parent, partner or provider are roles. They are important, but they do not describe the whole individual. A whole-person conversation makes room for what exists behind those roles."],
["When private support may be appropriate","Private wellbeing advisory can be considered when a person wants perspective, greater clarity, more sustainable boundaries or a confidential space to explore change. It is not a substitute for medical or psychological treatment when those forms of care are needed."]
]
};

export function JournalArticle({eyebrow,title,description,sections,related}:ArticleProps){
 const extended=[...(sections||[]),...(deepContent[title]||[])];
 const faqs=faqByTitle[title]||[["What is private wellbeing advisory?","A confidential, personalised space for reflection, wellbeing and personal direction."],["Who is it for?","Individuals who value discretion and a whole-person approach to demanding life circumstances."],["Can sessions be remote?","Yes, remote sessions can be arranged for Gulf and international clients."],["Does it replace medical or psychological care?","No. Appropriate qualified professionals should be involved when clinical care is required."]];
 const origin = typeof window !== "undefined" ? window.location.origin : "";
 const canonical = origin ? origin + window.location.pathname : window.location.pathname;
 const articleSchema = {
  "@context":"https://schema.org",
  "@type":"BlogPosting",
  "headline":title,
  "description":description,
  "inLanguage":"en",
  "author":{"@type":"Person","name":"Sourour Tarkan","url":origin ? origin + "/about" : "/about"},
  "publisher":{"@type":"Organization","name":"GULFWELLBEING"},
  "mainEntityOfPage":{"@type":"WebPage","@id":canonical},
  "image":origin ? [origin + "/images/sourour-tarkan-home.jpg"] : ["/images/sourour-tarkan-home.jpg"]
 };
 const faqSchema = {
  "@context":"https://schema.org",
  "@type":"FAQPage",
  "mainEntity": faqs.map(([q,a]) => ({
    "@type":"Question",
    "name":q,
    "acceptedAnswer":{"@type":"Answer","text":a}
  }))
 };
 const breadcrumbSchema = {
  "@context":"https://schema.org",
  "@type":"BreadcrumbList",
  "itemListElement":[
   {"@type":"ListItem","position":1,"name":"Home","item":origin ? origin + "/" : "/"},
   {"@type":"ListItem","position":2,"name":"Blog","item":origin ? origin + "/blog" : "/blog"},
   {"@type":"ListItem","position":3,"name":title,"item":canonical}
  ]
 };
 return <SiteShell><article>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(articleSchema)}} />
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumbSchema)}} />
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}} />
  <header className="page-hero"><div className="mx-auto max-w-4xl px-6 py-24 lg:px-12 lg:py-32"><p className="eyebrow text-gold">{eyebrow}</p><h1 className="mt-6 font-serif text-5xl leading-tight md:text-7xl">{title}</h1><p className="mt-7 max-w-3xl text-sm leading-7 text-muted-foreground">{description}</p></div></header>
  <figure className="mx-auto max-w-6xl px-6 pt-10 lg:px-12 lg:pt-16">
   <img src={stillLife} width={1408} height={1008} alt={title + " — GULFWELLBEING private wellbeing journal"} className="h-[38vh] w-full object-cover lg:h-[52vh]" loading="eager"/>
   <figcaption className="mt-3 text-xs uppercase tracking-[.16em] text-muted-foreground">GULFWELLBEING · Private Wellbeing Journal</figcaption>
  </figure>
  <div className="mx-auto grid max-w-6xl gap-16 px-6 py-20 lg:grid-cols-[1fr_.32fr] lg:px-12 lg:py-28">
   <div className="space-y-14">{extended.map(s=><section key={s[0]}><h2 className="font-serif text-3xl md:text-4xl">{s[0]}</h2><p className="mt-5 text-sm leading-7 text-muted-foreground">{s[1]}</p></section>)}
   <section className="border-t border-border pt-12"><p className="eyebrow text-gold">FAQ</p><h2 className="mt-4 font-serif text-4xl">Frequently asked questions</h2><div className="mt-8 divide-y divide-border">{faqs.map(([q,a])=><details key={q} className="py-5"><summary className="cursor-pointer font-medium">{q}</summary><p className="mt-3 max-w-3xl text-sm leading-7 text-muted-foreground">{a}</p></details>)}</div></section>
   <section className="border-t border-border pt-10"><p className="eyebrow text-gold">PRIVATE ENQUIRY</p><h2 className="mt-4 font-serif text-4xl">If this reflects what you are navigating, a private conversation can be the next step.</h2><Link to="/book" className="button-gold mt-7">Request a Private Session <ArrowRight className="size-4"/></Link></section></div>
   <aside className="lg:border-s lg:border-border lg:ps-10"><p className="eyebrow text-gold">EXPLORE</p><div className="mt-5 space-y-4">{related.map(r=><Link key={r.to} to={r.to} className="flex items-center justify-between border-b border-border pb-4 text-sm">{r.label}<ArrowRight className="size-4"/></Link>)}</div></aside>
  </div>
 </article></SiteShell>
}