import { Link } from "@tanstack/react-router";
import { ArrowRight, LockKeyhole } from "lucide-react";
import type { Section } from "@/lib/site-content";
import stillLife from "@/assets/private-still-life.jpg";
import womanImage from "@/assets/woman-editorial.jpg";
import executiveImage from "@/assets/executive-editorial.jpg";
const images: Record<string,string>={women:womanImage,men:executiveImage,business:stillLife,wellbeing:stillLife};
const related: Record<string,{title:string;to:string;body:string}[]>={
  wellbeing:[{title:"Women's Wellbeing",to:"/women",body:"Explore private advisory around motherhood, relationships, confidence and life transitions."},{title:"Men's Wellbeing",to:"/men",body:"Explore discreet support around pressure, fatherhood, leadership and personal direction."},{title:"Executive Wellbeing",to:"/business",body:"Private advisory for founders, executives and senior professionals."}],
  women:[{title:"Private Wellbeing Advisory",to:"/wellbeing",body:"Explore the broader Gulfwellbeing approach to stress, transitions and holistic wellbeing."},{title:"Men's Wellbeing",to:"/men",body:"Discover the wider private advisory practice."},{title:"Executive Wellbeing",to:"/business",body:"Private support for leadership pressure and responsibility."}],
  men:[{title:"Private Wellbeing Advisory",to:"/wellbeing",body:"Explore the wider approach to personal wellbeing and life transitions."},{title:"Women's Wellbeing",to:"/women",body:"Discover private advisory for women and family life."},{title:"Executive Wellbeing",to:"/business",body:"Explore private wellbeing advisory for leaders."}],
  business:[{title:"Private Wellbeing Advisory",to:"/wellbeing",body:"A broader approach to personal wellbeing, pressure and change."},{title:"Women's Wellbeing",to:"/women",body:"Private advisory for women navigating complex personal and family demands."},{title:"Men's Wellbeing",to:"/men",body:"Discreet support for men carrying professional and family responsibility."}]
};
export function EditorialPage({page,eyebrow,title,intro,sections}:{page:string;eyebrow:string;title:string;intro:string;sections:readonly Section[]}){return <><section className="page-hero"><div className="mx-auto grid min-h-[74vh] max-w-[1440px] items-center gap-12 px-6 py-20 lg:grid-cols-[1fr_.75fr] lg:px-12"><div className="reveal"><p className="eyebrow text-gold">{eyebrow}</p><h1 className="mt-7 max-w-4xl font-serif text-5xl leading-[1.02] md:text-7xl">{title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-muted-foreground">{intro}</p><Link to="/book" className="button-primary mt-9">Book a Private Session <ArrowRight className="size-4"/></Link></div><img src={images[page]} width={page==="wellbeing"?1408:1008} height={page==="wellbeing"?1008:1408} alt={title} className="h-[48vh] w-full object-cover object-center lg:h-[64vh]"/></div></section><section className="mx-auto max-w-[1440px] px-6 py-24 lg:px-12">{sections.map((s,i)=><article key={s.id} id={s.id} className="scroll-mt-28 grid gap-8 border-t border-border py-14 md:grid-cols-[120px_1fr_1fr] md:gap-12"><span className="font-serif text-3xl text-gold">{String(i+1).padStart(2,"0")}</span><h2 className="font-serif text-4xl">{s.title}</h2><div><p className="max-w-xl leading-8 text-muted-foreground">{s.body}</p><Link to="/book" className="mt-7 inline-flex items-center gap-2 text-sm font-medium">Begin a private conversation <ArrowRight className="size-4"/></Link></div></article>)}</section><section className="bg-secondary"><div className="mx-auto max-w-[1440px] px-6 py-20 lg:px-12"><p className="eyebrow text-gold">EXPLORE GULFWELLBEING</p><div className="mt-8 grid md:grid-cols-3">{(related[page]||[]).map(r=><Link key={r.to} to={r.to as any} className="group border-t border-border p-7 transition-colors hover:bg-background"><h3 className="font-serif text-3xl">{r.title}</h3><p className="mt-3 leading-7 text-muted-foreground">{r.body}</p><span className="mt-6 inline-flex items-center gap-2 text-sm">Explore <ArrowRight className="size-4 transition-transform group-hover:translate-x-2"/></span></Link>)}</div></div></section><section className="bg-secondary"><div className="mx-auto grid max-w-[1440px] gap-10 px-6 py-20 md:grid-cols-[auto_1fr_auto] md:items-center lg:px-12"><LockKeyhole className="size-10 text-gold"/><div><p className="eyebrow">PRIVATE & DISCREET</p><h2 className="mt-3 font-serif text-4xl">Support shaped around your circumstances.</h2></div><Link to="/book" className="button-primary">Book a Private Session</Link></div></section></>}