/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BookRouteImport } from './routes/book'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as MenRouteImport } from './routes/men'
import { Route as WellbeingRouteImport } from './routes/wellbeing'
import { Route as WomenRouteImport } from './routes/women'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as BusinessVipConciergeWellbeingRouteImport } from './routes/business/vip-concierge-wellbeing'
import { Route as BusinessExecutiveWellbeingRouteImport } from './routes/business/executive-wellbeing'
import { Route as MenFatherhoodRouteImport } from './routes/men/fatherhood'
import { Route as WellbeingStressBurnoutRouteImport } from './routes/wellbeing/stress-burnout'
import { Route as WomenMotherhoodRouteImport } from './routes/women/motherhood'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const MenRoute = MenRouteImport.update({
  id: '/men',
  path: '/men',
  getParentRoute: () => rootRouteImport,
} as any)
const WellbeingRoute = WellbeingRouteImport.update({
  id: '/wellbeing',
  path: '/wellbeing',
  getParentRoute: () => rootRouteImport,
} as any)
const WomenRoute = WomenRouteImport.update({
  id: '/women',
  path: '/women',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BusinessExecutiveWellbeingRoute = BusinessExecutiveWellbeingRouteImport.update({
  id: '/executive-wellbeing', path: '/executive-wellbeing', getParentRoute: () => BusinessRoute,
} as any)
const BusinessVipConciergeWellbeingRoute =
  BusinessVipConciergeWellbeingRouteImport.update({
    id: '/vip-concierge-wellbeing',
    path: '/vip-concierge-wellbeing',
    getParentRoute: () => BusinessRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/book': typeof BookRoute
  '/business': typeof BusinessRouteWithChildren
  '/men': typeof MenRoute
  '/wellbeing': typeof WellbeingRoute
  '/women': typeof WomenRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/business/vip-concierge-wellbeing': typeof BusinessVipConciergeWellbeingRoute
  '/business/executive-wellbeing': typeof BusinessExecutiveWellbeingRoute
  '/men/fatherhood': typeof MenFatherhoodRoute
  '/wellbeing/stress-burnout': typeof WellbeingStressBurnoutRoute
  '/women/motherhood': typeof WomenMotherhoodRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/book': typeof BookRoute
  '/business': typeof BusinessRouteWithChildren
  '/men': typeof MenRoute
  '/wellbeing': typeof WellbeingRoute
  '/women': typeof WomenRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/business/vip-concierge-wellbeing': typeof BusinessVipConciergeWellbeingRoute
  '/business/executive-wellbeing': typeof BusinessExecutiveWellbeingRoute
  '/men/fatherhood': typeof MenFatherhoodRoute
  '/wellbeing/stress-burnout': typeof WellbeingStressBurnoutRoute
  '/women/motherhood': typeof WomenMotherhoodRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/book': typeof BookRoute
  '/business': typeof BusinessRouteWithChildren
  '/men': typeof MenRoute
  '/wellbeing': typeof WellbeingRoute
  '/women': typeof WomenRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/business/vip-concierge-wellbeing': typeof BusinessVipConciergeWellbeingRoute
  '/business/executive-wellbeing': typeof BusinessExecutiveWellbeingRoute
  '/men/fatherhood': typeof MenFatherhoodRoute
  '/wellbeing/stress-burnout': typeof WellbeingStressBurnoutRoute
  '/women/motherhood': typeof WomenMotherhoodRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/book'
    | '/business'
    | '/men'
    | '/wellbeing'
    | '/women'
    | '/admin'
    | '/business/vip-concierge-wellbeing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/book'
    | '/business'
    | '/men'
    | '/wellbeing'
    | '/women'
    | '/admin'
    | '/business/vip-concierge-wellbeing'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/blog'
    | '/book'
    | '/business'
    | '/men'
    | '/wellbeing'
    | '/women'
    | '/_authenticated/admin'
    | '/business/vip-concierge-wellbeing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  BookRoute: typeof BookRoute
  BusinessRoute: typeof BusinessRouteWithChildren
  MenRoute: typeof MenRoute
  WellbeingRoute: typeof WellbeingRoute
  WomenRoute: typeof WomenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/men': {
      id: '/men'
      path: '/men'
      fullPath: '/men'
      preLoaderRoute: typeof MenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wellbeing': {
      id: '/wellbeing'
      path: '/wellbeing'
      fullPath: '/wellbeing'
      preLoaderRoute: typeof WellbeingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/women': {
      id: '/women'
      path: '/women'
      fullPath: '/women'
      preLoaderRoute: typeof WomenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/business/vip-concierge-wellbeing': {
      id: '/business/vip-concierge-wellbeing'
      path: '/vip-concierge-wellbeing'
      fullPath: '/business/vip-concierge-wellbeing'
      preLoaderRoute: typeof BusinessVipConciergeWellbeingRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/executive-wellbeing': { id: '/business/executive-wellbeing', path: '/executive-wellbeing', fullPath: '/business/executive-wellbeing', preLoaderRoute: typeof BusinessExecutiveWellbeingRouteImport, parentRoute: typeof BusinessRoute }
    '/men/fatherhood': { id: '/men/fatherhood', path: '/fatherhood', fullPath: '/men/fatherhood', preLoaderRoute: typeof MenFatherhoodRouteImport, parentRoute: typeof MenRoute }
    '/wellbeing/stress-burnout': { id: '/wellbeing/stress-burnout', path: '/stress-burnout', fullPath: '/wellbeing/stress-burnout', preLoaderRoute: typeof WellbeingStressBurnoutRouteImport, parentRoute: typeof WellbeingRoute }
    '/women/motherhood': { id: '/women/motherhood', path: '/motherhood', fullPath: '/women/motherhood', preLoaderRoute: typeof WomenMotherhoodRouteImport, parentRoute: typeof WomenRoute }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BusinessRouteChildren {
  BusinessVipConciergeWellbeingRoute: typeof BusinessVipConciergeWellbeingRoute
}

const BusinessRouteChildren: BusinessRouteChildren = {
  BusinessVipConciergeWellbeingRoute: BusinessVipConciergeWellbeingRoute,
}

const BusinessRouteWithChildren = BusinessRoute._addFileChildren(
  BusinessRouteChildren,
)
const MenFatherhoodRoute = MenFatherhoodRouteImport.update({ id: '/fatherhood', path: '/fatherhood', getParentRoute: () => MenRoute } as any)
const WellbeingStressBurnoutRoute = WellbeingStressBurnoutRouteImport.update({ id: '/stress-burnout', path: '/stress-burnout', getParentRoute: () => WellbeingRoute } as any)
const WomenMotherhoodRoute = WomenMotherhoodRouteImport.update({ id: '/motherhood', path: '/motherhood', getParentRoute: () => WomenRoute } as any)

const MenRouteWithChildren = MenRoute._addFileChildren({ MenFatherhoodRoute })
const WellbeingRouteWithChildren = WellbeingRoute._addFileChildren({ WellbeingStressBurnoutRoute })
const WomenRouteWithChildren = WomenRoute._addFileChildren({ WomenMotherhoodRoute })
const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  BookRoute: BookRoute,
  BusinessRoute: BusinessRouteWithChildren,
  MenRoute: MenRouteWithChildren,
  WellbeingRoute: WellbeingRouteWithChildren,
  WomenRoute: WomenRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
